name: Create Release

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      (github.event.workflow_run.conclusion == 'failure' &&
       !contains(toJson(github.event.workflow_run.jobs.*.name), 'build-and-test') &&
       !contains(toJson(github.event.workflow_run.jobs.*.name), 'codeql'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-4.8
          path: release_files

      - name: Prepare Display Files
        run: |
          mkdir -p release_files/Display
          cp -r Display/* release_files/Display/
          rm -rf release_files/Display/__pycache__

      - name: Create Zip Package
        run: |
          cd release_files
          zip -r ../OpenHardwareMonitor-Release.zip ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: OpenHardwareMonitor-Release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
