name: Create Release

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  create-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current date
        id: date
        run: |
          $date = Get-Date -Format "yyyy.MM.dd"
          echo "date=$date" >> $env:GITHUB_OUTPUT

      - name: Download .NET 4.8 Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: build-artifacts-4.8
          path: release_files
          workflow: ci-cd-pipeline.yml
          run_id: ${{ github.event.workflow_run.id }}
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Artifact Download
        run: |
          Write-Host "Contents of release_files:"
          Get-ChildItem -Recurse release_files
          if (-Not (Test-Path "release_files/OpenHardwareMonitor.exe")) {
            Write-Error "Error: OpenHardwareMonitor.exe not found!"
            exit 1
          }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install Psutil
        run: pip install psutil

      - name: Install Flask
        run: pip install flask

      - name: Install Waitress
        run: pip install waitress

      - name: Build Python EXE with PyInstaller
        run: |
          cd Display
          pyinstaller metrics_the_gathering.spec
          copy dist\metrics_the_gathering.exe ..\release_files\

      - name: Prepare Display Files
        run: |
          New-Item -ItemType Directory -Force -Path release_files\Display
          Copy-Item -Path Display\* -Destination release_files\Display -Recurse -Force
          Remove-Item -Path release_files\Display\__pycache__ -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path release_files\Display\*.pyc -Force -ErrorAction SilentlyContinue

      - name: Create Zip Package
        run: Compress-Archive -Path release_files\* -DestinationPath OpenHardwareMonitor-Release.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.date.outputs.date }}"
          name: "OpenHardwareMonitor v${{ steps.date.outputs.date }}"
          body: "Automatic release containing the latest build"
          files: OpenHardwareMonitor-Release.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
