name: Create Release

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: source-repo

      - name: Download .NET 4.8 Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build-artifacts-4.8
          path: release_files
          workflow: ci-cd-pipeline.yml
          run_id: ${{ github.event.workflow_run.id }}
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Artifact Download
        run: |
          echo "Contents of release_files:"
          ls -R release_files
          if [ ! -f "release_files/OpenHardwareMonitor.exe" ]; then
            echo "Error: OpenHardwareMonitor.exe not found!"
            exit 1
          fi

      - name: Prepare Display Files
        run: |
          echo "Contents of source-repo:"
          ls -R source-repo
          mkdir -p release_files/Display
          cp -r source-repo/Display/* release_files/Display/
          rm -rf release_files/Display/__pycache__
          rm -f release_files/Display/*.pyc

      - name: Create Zip Package
        run: |
          cd release_files
          zip -r ../OpenHardwareMonitor-Release.zip ./*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "OpenHardwareMonitor v$(date +'%Y.%m.%d')"
          body: "Automatic release containing the latest build"
          files: OpenHardwareMonitor-Release.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
